### PR TITLE
Adding Cx56_12 specialized footprints, Removing generic footprint

### PR DESCRIPTION
**Pull request by Misca1234**
Removed Cx56-12, it is a duplicate of CA56-12EWA

See 
https://github.com/KiCad/kicad-library/pull/1413

### CODE REVIEW

**Comment by poeschlr** [comment]
Will reomve once #2  is merged.

**Comment by poeschlr** [comment]
I had a few days thinking about this. I think the 7 segment displays should stay in this library. This would mean, you should move your currently open pull requests concerning 7 segment displays to this repo and maybe also move the 7 segment displays already merged. (I did not notice this lib exists until you created this pull request.)

My reasoning is that we plan to split the display symbol lib, so we should not merge the different footprint libs. (This should make the lib a bit more future proof. And it should make it easier for users to find symbols/footprints if they do not know what exactly they are looking for.)

**Comment by Misca1234** [comment]
I moved them from Displays.pretty to Displays_7-Segment.pretty

**Comment by poeschlr** [comment]
The clearance between the body and silk outline seems a bit large.
The courtyard clearance seems a bit large as well. (Shouldn't it be 0.25mm or is there a reason for it being larger for this footprints.)

**Comment by Misca1234** [comment]
I use 0.25 mm clearance
According to https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention 
the only two clearances are 7.3.ii.b an 5.iv.a, the first is 0.2 mm but for silk screen to pads and the second is only for F.CrtYrd, so i went with 0.25 for all lines
 

For example, the F.Fab line is at -1,88, 
-1,88 -0.25 - 0.06 = -2,19 
This is where the F.Silk line is, note that this is slightly to short because I do not subtract the half width line of F.fab) to get an exact 0.25 mm between F.Fab and F.Silk

F.CrtYrd is slightly off, it should for example be at -2,465 on the left side, I fix it

**Comment by poeschlr** [comment]
courtyard is measured from part body. Fab is the part body which means courtyard should be 0.25 outside fab center line.
(center fab to center courtyard = 0.25mm)
The silk line only needs the 0.2mm clearance to the pads. (this is to avoid bleeding of silk onto exposed copper)
The pads are far away from the part outline which means you can create the silk outline such that it is just outside the fab outline. (i normally add the full silk line width to the fab coordinates.)

**Comment by Misca1234** [comment]
They all look like this now 

bild

bild

**Comment by poeschlr** [comment]
Looks good. Thanks for your contribution.

**Comment by Misca1234** [comment]
Thanks

**Pull request merged**
