### PR TITLE
Da dc04 11

### PR DESCRIPTION
**Pull request by Misca1234**
Push for DA04-11 and DC04-11

kicad-library push branch is 
https://github.com/KiCad/kicad-library/pull/1456

Displays_7-Segment.pretty push branch is 
https://github.com/KiCad/Displays_7-Segment.pretty/pull/10

packages3D push branch is 
https://github.com/KiCad/packages3D/pull/96

packages3D-source push branch is 
https://github.com/KiCad/packages3D-source/pull/30

DA04-11CGKWA
http://www.kingbright.com/attachments/file/psearch/000/00/00/DA04-11CGKWA(Ver.6A).pdf

DA04-11EWA
http://www.kingbrightusa.com/images/catalog/SPEC/DA04-11EWA.pdf

DA04-11GWA 
http://www.kingbrightusa.com/images/catalog/SPEC/DA04-11GWA.pdf

DA04-11SRWA
http://www.kingbrightusa.com/images/catalog/SPEC/DA04-11SRWA.pdf

DA04-11SEKWA
http://www.kingbright.com/attachments/file/psearch/000/00/00/DA04-11SEKWA(Ver.9A).pdf

DA04-11SURKWA
http://www.kingbright.com/attachments/file/psearch/000/00/00/DA04-11SURKWA(Ver.10A).pdf

DA04-11SYKWA 
http://www.kingbright.com/attachments/file/psearch/000/00/00/DA04-11SYKWA(Ver.6A).pdf

DA04-11YWA
http://www.kingbrightusa.com/images/catalog/SPEC/DA04-11YWA.pdf

DC04-11CGKWA
http://www.kingbright.com/attachments/file/psearch/000/00/00/DC04-11CGKWA(Ver.7A).pdf

DC04-11GWA 
http://www.kingbrightusa.com/images/catalog/SPEC/DC04-11GWA.pdf

DC04-11SEKWA
http://www.kingbright.com/attachments/file/psearch/000/00/00/DC04-11SEKWA(Ver.7A).pdf

DC04-11SURKWA 
http://www.kingbright.com/attachments/file/psearch/000/00/00/DC04-11SURKWA(Ver.6A).pdf

DC04-11SYKWA 
http://www.kingbright.com/attachments/file/psearch/000/00/00/DC04-11SYKWA(Ver.6A).pdf

bild

bild

### CODE REVIEW

**Comment by poeschlr** [comment]
The footprint names should indicate that they are used for multiple components. Maybe simply Dx04_color?

**Comment by Misca1234** [comment]
If it is al right with you I would prefer not to change it.
this is the "same method" have been used on all the other pushes.

**Comment by poeschlr** [comment]
I should have complained in earlier pull requests then. (I did not notice this.)

I feel the lib as a whole would benefit from renaming the footprints to clearly show that they represent multiple parts. If you are prepared to do it for still open pull requests that would be great. Otherwise i can merge them as they are.
This would mean i need to invest time later on to fix them with a pull request of my own.

**Comment by poeschlr** [comment]
Pin 1 is near enough to a corner that you can use a simple chamfer for the pin 1 marker. And an 'L' around the corner on silk.
28674000-6771812e-72e4-11e7-9ed3-0ba619a4ca01

**Comment by Misca1234** [comment]
They look like this now 

bild

**Comment by Misca1234** [comment]
> I feel the lib as a whole would benefit from renaming the footprints to clearly show that they represent multiple parts.

Lets do it when all my pushes is in so the current "way of working" is not disrupted and there is a complete overview. In the same push we can also remove those which can not be traced or is redundant.

**Comment by poeschlr** [comment]
What about pin 1 marker on fab? I think here a simple chamfer would be suited better.

**Comment by Misca1234** [comment]
They look like this now 

bild

**Comment by Misca1234** [comment]
Like this 

bild

**Comment by poeschlr** [comment]
Thanks

**Pull request merged**
