### PR TITLE
De 113 rs 20

### PR DESCRIPTION
**Pull request by Misca1234**
Here is the replacement for the old DE-113-RS-20 displays

I added all three types and their variants from display-elektronik
wich have the same size and form factor as the DE-113-RS-20

There are 3 main symbols and the rest are aliases to those
DE 113-MS-20/7,5
DE 114-RS-20/6,35
DE 170-RS-20/7,5

I only added the 3D model of the 6.35mm pin lenght varaints, 
if you want I can add all variants as well, including 3D models

kicad-library push branch is 
https://github.com/KiCad/kicad-library/pull/1454

pretty push branch is 
https://github.com/KiCad/Displays_7-Segment.pretty/pull/8

packages3D push branch is 
https://github.com/KiCad/packages3D-source/pull/28

packages3D-source push branch is 
https://github.com/KiCad/packages3D/pull/94

DE 113-MS-20/7,5
http://www.display-elektronik.de/filter/DE113-RS-20_122.pdf

DE 113-RS-20/12,2
http://www.display-elektronik.de/filter/DE113-RS-20_122.pdf

DE 113-RS-20/6,35
http://www.display-elektronik.de/filter/DE113-RS-20_635.pdf

DE 113-RS-20/7,5
http://www.display-elektronik.de/filter/DE113-RS-20_75.pdf

DE 113-RS-20/8,4
http://www.display-elektronik.de/filter/DE113-RS-20_84.pdf

DE 113-RU-30/7,5
http://www.display-elektronik.de/filter/DE113-RU-30_75.pdf

DE 113-TS-20/7,5
http://www.display-elektronik.de/filter/DE113-TS-20_75.pdf

DE 113-TU-30/8,4
http://www.display-elektronik.de/filter/DE113-TU-30_84.pdf

DE 114-RS-20/6,35
http://www.display-elektronik.de/filter/DE114-RS-20_635.pdf

DE 114-RS-20/7,5
http://www.display-elektronik.de/filter/DE113-MS-20_75.pdf

DE 114-RS-20/8,4
http://www.display-elektronik.de/filter/DE114-RS-20_84.pdf

DE 170-RS-20/7,5
http://www.display-elektronik.de/filter/DE170-RS-20_75.pdf

DE 170-RU-30/6,35
http://www.display-elektronik.de/filter/DE170-RU-30_635.pdf

DE 170-TS-20/6,35
http://www.display-elektronik.de/filter/DE170-TS-20_635.pdf

bild

### CODE REVIEW

**Comment by poeschlr** [comment]
If the display is meant to be mounted as low as it seems from your 3d model placement, we might want to include some sort of keepout area where the pins connect with the display. (There is a danger to create a short circuit.
For how this should look like have a look here: https://github.com/KiCad/kicad-library/issues/1443 (Maybe wait a few days until an official decision is reached.)

The pin 1 marker would look better if it would be an inverted `L`. Maybe use a distance to the drill center that is large enough to be outside a pin header if a user uses a pin header to connect the display.
screenshot from 2017-07-29 20-43-24

**Comment by Misca1234** [comment]
Becosue all the models have different pin lenght and som pins are long, I guess it is meant to be mounted "high" above the PCB to "reach" the box top side, but I fix the distance thing anyway in case someone mount it close to the PCB

**Comment by Misca1234** [comment]
bild

**Comment by poeschlr** [comment]
Thanks.
I notice here you use the xx notation to show that a footprint represents multiple components ;)

**Comment by Misca1234** [comment]
Thx

**Pull request merged**
