### PR TITLE
add Cx56-12 4-digit 7-segment LED display

### PR DESCRIPTION
**Pull request by Fat-Zer**
Here is a matching footprint for recent pull request to the schematic library https://github.com/KiCad/kicad-library/pull/201

Please be kind pointing out mistakes: it's my first footprint commit.

### CODE REVIEW

**Comment by CarlPoirier** [comment]
Hi,

You don't have much left to adjust. Please simply set the footprint anchor on pin one as per rule 6.3. Then, add courtyard according to rules 6.6 and 6.7 and that will be it.

Thanks!

**Comment by Fat-Zer** [comment]
Done, take a look...

**Comment by ricardocrudo** [comment]
@Fat-Zer could you please fix the courtyard grid rounding? You could try use the option --fix of the [check_kicad_mod](https://github.com/KiCad/kicad-library-utils/tree/master/pcb) script.

**Comment by ricardocrudo** [comment]
Hi @Fat-Zer. The pinout is wrong. Maybe you could turn the footprint 90 degrees clockwise, as KLC say "Pad 1 is on the left first, then at the top".

**Comment by Fat-Zer** [comment]
> "Pad 1 is on the left first, then at the top". 
I reed this as "First pad must be the utmost left, and if it make sense it should be on the top".
It's a bit silly to rotate the footprint in this case, isn't it?

**Comment by ricardocrudo** [comment]
> I reed this as "First pad must be the utmost left, and if it make sense it should be on the top".
It's a bit silly to rotate the footprint in this case, isn't it?

I don't know if the rules have to be strictly followed, we can hear what others librarians have to say.

But what I meant with wrong pinout isn't about the "rotation", the thing is that superior pins sequence is wrong: *12, 11, 10, 7, 8, 9* should be: *12, 11, 10, 9, 8, 7*

**Comment by Fat-Zer** [comment]
>But what I meant with wrong pinout isn't about the "rotation", the thing is that superior pins sequence is wrong: 12, 11, 10, 7, 8, 9 should be: 12, 11, 10, 9, 8, 7

My bad, thanks for the notice...

**Comment by ricardocrudo** [comment]
thank you.

**Pull request merged**
